#
# -This YAML  manifest file contains two kubernetes resources for the video-streaming microservice.
#  - One Deployment, and one Service for the Deployment's Pods.
#  - Notice how multiple resources can be defined in one YAML file by separating them with 3 dashes ---
# 
# Note!
# The placeholders below have to be replaced before deploying the manifest to kubernetes:
#   $CONTAINER_REGISTRY_LOGIN_SERVER
#   $VERSION
#
# This can be done by creating environment variables in Linux as below:
#   export CONTAINER_REGISTRY_LOGIN_SERVER=<your-container-registry>
#   export VERSION=<the-version-to-deploy>
#
# Then replace the placeholders and deploy the manifest using the Linux command below:
#   envsubst < ./scripts/kubernetes/deploy.yaml | kubectl apply -f -
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: OskarTest123
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OskarTest123
  template:
    metadata:
      labels:
        app: OskarTest123
    spec:
      containers: 
      - name: OskarTest123
        image: $CONTAINER_REGISTRY_LOGIN_SERVER/OskarTest123:$VERSION
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "4000"
        resources:
          requests:
            cpu: 126m
            memory: 126Mi
          limits:
            cpu: 256m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: OskarTest123
spec:
  selector:
    app: OskarTest123
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000